# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Louis Roy
email: louisroy@louisroy.net
description: > # this means to ignore newlines until "baseurl:"
  I'm Louis. This is where I write small articles about some of the stuff I like, namely :
  music, technology, DIY projects and photography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.louisroy.net" # the base hostname & protocol for your site
github_username:  louisroy

# Build settings
markdown: kramdown

gems:
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-redirect-from
